package com.nliven.android.airports.biz.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.nliven.android.airports.biz.model.Airport;

import com.nliven.android.airports.biz.dao.AirportDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig airportDaoConfig;

    private final AirportDao airportDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        airportDaoConfig = daoConfigMap.get(AirportDao.class).clone();
        airportDaoConfig.initIdentityScope(type);

        airportDao = new AirportDao(airportDaoConfig, this);

        registerDao(Airport.class, airportDao);
    }
    
    public void clear() {
        airportDaoConfig.getIdentityScope().clear();
    }

    public AirportDao getAirportDao() {
        return airportDao;
    }

}
